USE ROLE ACCOUNTADMIN; 
USE WAREHOUSE COMPUTE_WH; 

CREATE OR REPLACE DATABASE WALMART; 


CREATE OR REPLACE STORAGE INTEGRATION SNOWFLAKE_WALMART_S3_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::127549748722:role/Walmart_project_snowflake_role'
    STORAGE_ALLOWED_LOCATIONS = ('s3://walmart-bi-dea/data/'); 

-- Edit trust relationship in aws role 

DESC INTEGRATION SNOWFLAKE_WALMART_S3_INT; 
-- Get values: 
-- STORAGE_AWS_EXTERNAL_ID 
-- STORAGE_AWS_IAM_USER_ARN
-- Paste into trust relationship aws role

-- Create external stage in snowflake to house s3 data 
CREATE OR REPLACE FILE FORMAT WALMART_CSV_FF
  TYPE = CSV
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('NULL', 'null','NA')
  EMPTY_FIELD_AS_NULL = true
  TRIM_SPACE = TRUE;

CREATE OR REPLACE STAGE WALMART.PUBLIC.WALMART_DATA_STAGE
STORAGE_INTEGRATION = SNOWFLAKE_WALMART_S3_INT
URL= 's3://walmart-bi-dea/data/' 
FILE_FORMAT = WALMART.PUBLIC.WALMART_CSV_FF;

LIST @WALMART_DATA_STAGE;
-- See 3 csv files 

-- Grant access to dbt role accountadmin 
GRANT USAGE ON DATABASE WALMART TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA WALMART.PUBLIC TO ROLE ACCOUNTADMIN;
GRANT USAGE ON FILE FORMAT WALMART.PUBLIC.WALMART_CSV_FF TO ROLE ACCOUNTADMIN;
GRANT USAGE ON STAGE WALMART.PUBLIC.WALMART_DATA_STAGE TO ROLE ACCOUNTADMIN;


